-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 20:38:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wake
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wake` ;

-- -----------------------------------------------------
-- Schema wake
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wake` DEFAULT CHARACTER SET utf8 ;
USE `wake` ;

-- -----------------------------------------------------
-- Table `wake`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `wake`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `Morada` VARCHAR(45) NULL,
  `Morada de Faturação` VARCHAR(45) NULL,
  `Peso` INT NULL,
  `Altura` INT NULL,
  `Genero` VARCHAR(45) NULL,
   `Estilo_idEstilo1` INT NULL,
    FOREIGN KEY (`Estilo_idEstilo1`)
    REFERENCES `wake`.`Estilo` (`idEstilo`),
  UNIQUE INDEX `Email_Cliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Estilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Estilo` ;

CREATE TABLE IF NOT EXISTS `wake`.`Estilo` (
  `idEstilo` INT NOT NULL auto_increment,
  `Nome_Estilo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstilo`),
  UNIQUE INDEX `idEstilo_UNIQUE` (`idEstilo` ASC) VISIBLE,
  UNIQUE INDEX `Nome_Estilo_UNIQUE` (`Nome_Estilo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Formulario` ;

CREATE TABLE IF NOT EXISTS `wake`.`Formulario` (
  `idFormulario` INT NOT NULL auto_increment,
  `Resposta 1` INT NULL,
   `Resposta 2` INT NULL,
    `Resposta 3` INT NULL,
     `Resposta 4` INT NULL,
     `Resposta 5` INT NULL,
      `Resposta 6` INT NULL,
       `Resposta 7` INT NULL,
        `Resposta 8` INT NULL,
         `Resposta 9` INT NULL,
          `Resposta 10` INT NULL,
            `Resposta 11` INT NULL,
             `Resposta 12` INT NULL,
              `Resposta 13` INT NULL,
               `Resposta 14` INT NULL,
                `Resposta 15` INT NULL,
      
  `Cliente_idCliente` INT NOT NULL,
  `Estilo_idEstilo1` INT NOT NULL,
  PRIMARY KEY (`idFormulario`),
  UNIQUE INDEX `idFormulário_UNIQUE` (`idFormulario` ASC) VISIBLE,
  INDEX `fk_Formulário_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Formulario_Estilo1_idx` (`Estilo_idEstilo1` ASC) VISIBLE,
  CONSTRAINT `fk_Formulário_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `wake`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formulario_Estilo1`
    FOREIGN KEY (`Estilo_idEstilo1`)
    REFERENCES `wake`.`Estilo` (`idEstilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Roupa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Roupa` ;

CREATE TABLE IF NOT EXISTS `wake`.`Roupa` (
  `idRoupa` INT NOT NULL AUTO_INCREMENT,
  `URL` varchar(500) NULL,
  `Genero` varchar(25) NULL,
  -- Fazer Insert Roupas
  PRIMARY KEY (`idRoupa`),
  UNIQUE INDEX `idRoupa_UNIQUE` (`idRoupa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Pacote` ;

CREATE TABLE IF NOT EXISTS `wake`.`Pacote` (
  `idPacote` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPacote`),
  UNIQUE INDEX `idPacote_UNIQUE` (`idPacote` ASC) VISIBLE,
  INDEX `fk_Pacote_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pacote_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `wake`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Estilo_Roupa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Estilo_Roupa` ;

CREATE TABLE IF NOT EXISTS `wake`.`Estilo_Roupa` (
  `Estilo_idEstilo` INT NOT NULL,
  `Roupa_idRoupa` INT NOT NULL,
  PRIMARY KEY (`Estilo_idEstilo`, `Roupa_idRoupa`),
  INDEX `fk_Estilo_has_Roupa_Roupa1_idx` (`Roupa_idRoupa` ASC) VISIBLE,
  INDEX `fk_Estilo_has_Roupa_Estilo1_idx` (`Estilo_idEstilo` ASC) VISIBLE,
  CONSTRAINT `fk_Estilo_has_Roupa_Estilo1`
    FOREIGN KEY (`Estilo_idEstilo`)
    REFERENCES `wake`.`Estilo` (`idEstilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estilo_has_Roupa_Roupa1`
    FOREIGN KEY (`Roupa_idRoupa`)
    REFERENCES `wake`.`Roupa` (`idRoupa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wake`.`Conteudo_Pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Conteudo_Pacote` ;

CREATE TABLE IF NOT EXISTS `wake`.`Conteudo_Pacote` (
  `Pacote_idPacote` INT NOT NULL,
  `Estilo_Roupa_Estilo_idEstilo` INT NOT NULL,
  `Estilo_Roupa_Roupa_idRoupa` INT NOT NULL,
  PRIMARY KEY (`Pacote_idPacote`, `Estilo_Roupa_Estilo_idEstilo`, `Estilo_Roupa_Roupa_idRoupa`),
  INDEX `fk_Pacote_has_Estilo_Roupa_Estilo_Roupa1_idx` (`Estilo_Roupa_Estilo_idEstilo` ASC, `Estilo_Roupa_Roupa_idRoupa` ASC) VISIBLE,
  INDEX `fk_Pacote_has_Estilo_Roupa_Pacote1_idx` (`Pacote_idPacote` ASC) VISIBLE,
  CONSTRAINT `fk_Pacote_has_Estilo_Roupa_Pacote1`
    FOREIGN KEY (`Pacote_idPacote`)
    REFERENCES `wake`.`Pacote` (`idPacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacote_has_Estilo_Roupa_Estilo_Roupa1`
    FOREIGN KEY (`Estilo_Roupa_Estilo_idEstilo` , `Estilo_Roupa_Roupa_idRoupa`)
    REFERENCES `wake`.`Estilo_Roupa` (`Estilo_idEstilo` , `Roupa_idRoupa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `wake`.`Conteudo_Pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wake`.`Conteudo_Pacote` ;
DROP TABLE IF EXISTS `wake`.`Estilo_Roupa` ;
DROP TABLE IF EXISTS `wake`.`Roupa` ;

- -----------------------------------------------------
-- Table `wake`.`Roupa`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wake`.`Roupa` (
  `idRoupa` INT NOT NULL AUTO_INCREMENT,
  `URL` varchar(500) NULL,
  `Genero` varchar(25) NULL,
  `Tipo` varchar(25) NULL,
  `Preco` INT NULL,
  -- Fazer Insert Roupas
  PRIMARY KEY (`idRoupa`),
  UNIQUE INDEX `idRoupa_UNIQUE` (`idRoupa` ASC) VISIBLE)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `wake`.`Estilo_Roupa`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wake`.`Estilo_Roupa` (
  `Estilo_idEstilo` INT NOT NULL,
  `Roupa_idRoupa` INT NOT NULL,
  PRIMARY KEY (`Estilo_idEstilo`, `Roupa_idRoupa`),
  INDEX `fk_Estilo_has_Roupa_Roupa1_idx` (`Roupa_idRoupa` ASC) VISIBLE,
  INDEX `fk_Estilo_has_Roupa_Estilo1_idx` (`Estilo_idEstilo` ASC) VISIBLE,
  CONSTRAINT `fk_Estilo_has_Roupa_Estilo1`
    FOREIGN KEY (`Estilo_idEstilo`)
    REFERENCES `wake`.`Estilo` (`idEstilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estilo_has_Roupa_Roupa1`
    FOREIGN KEY (`Roupa_idRoupa`)
    REFERENCES `wake`.`Roupa` (`idRoupa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `wake`.`Conteudo_Pacote` (
  `Pacote_idPacote` INT NOT NULL,
  `Estilo_Roupa_Estilo_idEstilo` INT NOT NULL,
  `Estilo_Roupa_Roupa_idRoupa` INT NOT NULL,
  PRIMARY KEY (`Pacote_idPacote`, `Estilo_Roupa_Estilo_idEstilo`, `Estilo_Roupa_Roupa_idRoupa`),
  INDEX `fk_Pacote_has_Estilo_Roupa_Estilo_Roupa1_idx` (`Estilo_Roupa_Estilo_idEstilo` ASC, `Estilo_Roupa_Roupa_idRoupa` ASC) VISIBLE,
  INDEX `fk_Pacote_has_Estilo_Roupa_Pacote1_idx` (`Pacote_idPacote` ASC) VISIBLE,
  CONSTRAINT `fk_Pacote_has_Estilo_Roupa_Pacote1`
    FOREIGN KEY (`Pacote_idPacote`)
    REFERENCES `wake`.`Pacote` (`idPacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacote_has_Estilo_Roupa_Estilo_Roupa1`
    FOREIGN KEY (`Estilo_Roupa_Estilo_idEstilo` , `Estilo_Roupa_Roupa_idRoupa`)
    REFERENCES `wake`.`Estilo_Roupa` (`Estilo_idEstilo` , `Roupa_idRoupa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcao1.jpg', 'male', 'calcoes', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcao2.jpg', 'male', 'calcoes', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcao3.jpg', 'male', 'calcoes', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcas1.jpg', 'male', 'calça', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcas2.jpg', 'male', 'calça', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_calcas3.jpg', 'male', 'calça', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisa1.jpg', 'male', 'camisa', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisa2.jpg', 'male', 'camisa', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisa3.jpg', 'male', 'camisa', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisola1.jpg', 'male', 'camisola', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisola2.jpg', 'male', 'camisola', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_camisola3.jpg', 'male', 'camisola', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_casaco1.jpg', 'male', 'casaco', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_casaco2.jpg', 'male', 'casaco', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_casaco3.jpg', 'male', 'casaco', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_sweatshirt1.jpg', 'male', 'sweat', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_sweatshirt2.jpg', 'male', 'sweat', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_sweatshirt3.jpg', 'male', 'sweat', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_tshirt1.jpg', 'male', 'tshirt', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_tshirt2.jpg', 'male', 'tshirt', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/alterno_tshirt3.jpg', 'male', 'tshirt', '30');

INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcao1.jpg', 'male', 'calcoes', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcao2.jpg', 'male', 'calcoes', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcao3.jpg', 'male', 'calcoes', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcas1.jpg', 'male', 'calça', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcas2.jpg', 'male', 'calça', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_calcas3.jpg', 'male', 'calça', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisa1.jpg', 'male', 'camisa', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisa2.jpg', 'male', 'camisa', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisa3.jpg', 'male', 'camisa', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisola1.jpg', 'male', 'camisola', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisola2.jpg', 'male', 'camisola', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_camisola3.jpg', 'male', 'camisola', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_casaco1.jpg', 'male', 'casaco', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_casaco2.jpg', 'male', 'casaco', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_casaco3.jpg', 'male', 'casaco', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_sweatshirt1.jpg', 'male', 'sweat', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_sweatshirt2.jpg', 'male', 'sweat', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_sweatshirt3.jpg', 'male', 'sweat', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_tshirt1.jpg', 'male', 'tshirt', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_tshirt2.jpg', 'male', 'tshirt', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/classic_tshirt3.jpg', 'male', 'tshirt', '30');

INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcao1.jpg', 'male', 'calcoes', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcao2.jpg', 'male', 'calcoes', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcao3.jpg', 'male', 'calcoes', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcas1.jpg', 'male', 'calça', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcas2.jpg', 'male', 'calça', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_calcas3.jpg', 'male', 'calça', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisa1.jpg', 'male', 'camisa', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisa2.jpg', 'male', 'camisa', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisa3.jpg', 'male', 'camisa', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisola1.jpg', 'male', 'camisola', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisola2.jpg', 'male', 'camisola', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_camisola3.jpg', 'male', 'camisola', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_casaco1.jpg', 'male', 'casaco', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_casaco2.jpg', 'male', 'casaco', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_casaco3.jpg', 'male', 'casaco', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_sweatshirt1.jpg', 'male', 'sweat', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_sweatshirt2.jpg', 'male', 'sweat', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_sweatshirt3.jpg', 'male', 'sweat', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_tshirt1.jpg', 'male', 'tshirt', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_tshirt2.jpg', 'male', 'tshirt', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/desportivo_tshirt3.jpg', 'male', 'tshirt', '30');

INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcao1.jpg', 'male', 'calcoes', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcao2.jpg', 'male', 'calcoes', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcao3.jpg', 'male', 'calcoes', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcas1.jpg', 'male', 'calça', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcas2.jpg', 'male', 'calça', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_calcas3.jpg', 'male', 'calça', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisa1.jpg', 'male', 'camisa', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisa2.jpg', 'male', 'camisa', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisa3.jpg', 'male', 'camisa', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisola1.jpg', 'male', 'camisola', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisola2.jpg', 'male', 'camisola', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_camisola3.jpg', 'male', 'camisola', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_casaco1.jpg', 'male', 'casaco', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_casaco2.jpg', 'male', 'casaco', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_casaco3.jpg', 'male', 'casaco', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_sweatshirt1.jpg', 'male', 'sweat', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_sweatshirt2.jpg', 'male', 'sweat', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_sweatshirt3.jpg', 'male', 'sweat', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_tshirt1.jpg', 'male', 'tshirt', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_tshirt2.jpg', 'male', 'tshirt', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/flannel_tshirt3.jpg', 'male', 'tshirt', '30');

INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcao1.jpg', 'male', 'calcoes', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcao2.jpg', 'male', 'calcoes', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcao3.jpg', 'male', 'calcoes', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcas1.jpg', 'male', 'calça', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcas2.jpg', 'male', 'calça', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_calcas3.jpg', 'male', 'calça', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisa1.jpg', 'male', 'camisa', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisa2.jpg', 'male', 'camisa', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisa3.jpg', 'male', 'camisa', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisola1.jpg', 'male', 'camisola', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisola2.jpg', 'male', 'camisola', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_camisola3.jpg', 'male', 'camisola', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_casaco1.jpg', 'male', 'casaco', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_casaco2.jpg', 'male', 'casaco', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_casaco3.jpg', 'male', 'casaco', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_sweatshirt1.jpg', 'male', 'sweat', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_sweatshirt2.jpg', 'male', 'sweat', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_sweatshirt3.jpg', 'male', 'sweat', '30');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_tshirt1.jpg', 'male', 'tshirt', '10');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_tshirt2.jpg', 'male', 'tshirt', '20');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`, `Tipo`, `Preco`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/homem_pacote/streetwear_tshirt3.jpg', 'male', 'tshirt', '30');

#inserir roupa mulher
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/boho_estrang.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/boho_stradivarius.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/boho_stradivarius2.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/casual_lemot.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/casual_parfois.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/classico_f_isto.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/classico_f_malhas.png', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/comfy_conscious.png', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/comfy_conscious2.png', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/comfy_conscious3.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/comfy_estrang.png', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/streetwear_f_estrang.jpg', 'female');
INSERT INTO `wake`.`roupa` (`URL`, `Genero`) VALUES ('https://raw.githubusercontent.com/hmpms-iscte/wake/main/wake_img/mulher_pacote/streetwear_f_estrang2.jpg', 'female');

INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('boho');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('alterno');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('comfy');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('casual');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('classic');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('streetwear');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('desportivo');
INSERT INTO `wake`.`estilo` (`Nome_Estilo`) VALUES ('flannel');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '1');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '2');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '3');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '4');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '5');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '6');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '7');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '8');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '9');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '10');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '11');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '12');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '13');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '14');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '15');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '16');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '17');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '18');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '19');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '20');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('2', '21');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '22');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '23');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '24');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '25');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '26');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '27');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '28');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '29');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '30');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '31');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '32');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '33');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '34');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '35');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '36');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '37');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '38');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '39');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '40');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '41');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '42');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '43');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '44');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '45');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '46');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '47');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '48');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '49');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '50');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '51');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '52');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '53');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '54');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '55');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '56');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '57');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '58');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '59');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '60');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '61');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '62');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('7', '63');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '64');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '65');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '66');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '67');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '68');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '69');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '70');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '71');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '72');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '73');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '74');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '75');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '76');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '77');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '78');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '79');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '80');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '81');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '82');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '83');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('8', '84');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '85');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '86');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '87');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '88');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '89');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '90');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '91');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '92');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '93');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '94');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '95');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '96');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '97');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '98');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '99');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '100');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '101');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '102');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '103');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '104');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '105');



INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('1', '106');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('1', '107');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('1', '108');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('4', '109');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('4', '110');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '111');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('5', '112');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('3', '113');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('3', '114');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('3', '115');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('3', '116');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '117');
INSERT INTO `wake`.`estilo_roupa` (`Estilo_idEstilo`, `Roupa_idRoupa`) VALUES ('6', '118');